########################################################################################################################
log_level = "DEBUG" # Уровень журналирования (возможная опечатка, должно быть "log_level")
log_path = ""       # Путь к файлу журнала configs/kronoskeeper.log
########################################################################################################################


########################################################################################################################
### Настройка уведомлений
[telegram]
token = ""   # API ключ Telegram (введите ваш собственный ключ)
chat_id = ""
########################################################################################################################


########################################################################################################################
### Настройка удаленных хранилищ данных
[storage]
[storage.gCloud]
credentials_json = "configs/credentials.json" # Путь к JSON-файлу с учетными данными для Google Drive

[storage.samba]
samba = "//server/share" # Путь к сетевому ресурсу Samba
username = "username"    # Имя пользователя для доступа к ресурсу
password = "password"    # Пароль для доступа к ресурсу

[storage.nfs]
path = "/path/to/nfs/share"         # Путь к NFS-шаре
mount_options = "ro,soft,timeo=900" # Опции монтирования (read-only, soft, timeout=900)


### Настройка юнитов/задач бекапов
[[Unit]]
name = "nginx"                       # Имя юнита/задачи бэкапа
retention = 30                       # Время хранения бэкапов (в днях)
crontabTask = "* * * * * *"          # Расписание Cron 
input = ["/tmp/test", "/tmp/test2"]  # Пути для бэкапа
output = "/tmp"                      # Путь для сохранения бэкапов
compressFormat = "zip"               # Формат сжатия бэкапов
compressExclude = ["file1", "*.zip"] # Исключения из сжатия
maxDiskUsage = ""                    # Максимальное использование диска (можно установить ограничение)
remotestorages = ["gCloud"]          # Список удаленных хранилищ, куда отправлять бэкапы
remoteDir = "hostnamemyserver"       # Папка на удаленном хранилище для сохранения бэкапов
